name: GitHub CICD Pipeline
on: [push]

jobs:

##### build #########################################################
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building ${{ env.GITHUB_JOB }}...."

  build_job_2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building ${{ env.GITHUB_JOB }}...."

##### test #########################################################
  test:
    runs-on: ubuntu-latest
    needs: [build_job_1, build_job_2]
    steps:
      - name: unit test
        run: echo "unit test with pytest...."

      - name: linting check
        run: echo "static code analyze with pylint...."
  
      - name: codestyle check
        run: echo "pycodestyle (pep8) check with flake8...."

      - name: tpye check
        run: echo "static type check with mypy...."

      - name: security check
        run: echo "security check with bandit...."

##### deploy #########################################################

  dev-deploy:
    needs: [test]
    if: contains(github.ref, 'develop')
    runs-on: ubuntu-latest
    steps:
      - name: deploy dev project
        run: echo "This job will run after test is complete for $PROJECT_ID"
        env:
          GCP_APP_BUCKET: "PROJECT_DEV_BUCKET_NAME"
          PROJECT_ID: ${{ secrets.GCP_PROJECT_DEV }}
      
  test-deploy:
    needs: [test]
    if: contains(github.ref, '/^release.*$/') || contains(github.ref, '/^hotfix.*$/')
    runs-on: ubuntu-latest
    steps:
      - name: deploy test project
        run: echo "This job will run after test is complete for $PROJECT_ID"
        env:
          GCP_APP_BUCKET: "PROJECT_TEST_BUCKET_NAME"
          PROJECT_ID: ${{ secrets.GCP_PROJECT_TEST }}

  prod-deploy:
    needs: [test]
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: deploy prod project
        run: echo "This job will run after test is complete for $PROJECT_ID"
        env:
          GCP_APP_BUCKET: "PROJECT_PROD_BUCKET_NAME"
          PROJECT_ID: ${{ secrets.GCP_PROJECT_PROD }}

##### publish #########################################################


##### versioning #########################################################


##### test_production #########################################################




