name: GitHub CICD Pipeline
on: [push]

jobs:

##### build #########################################################
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building ${{ env.GITHUB_JOB }}...."

  build_job_2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building ${{ env.GITHUB_JOB }}...."

##### test #########################################################
  test:
    runs-on: ubuntu-latest
    needs: [build_job_1, build_job_2]
    steps:
      - run: echo "unit test with pytest...."
      - run: echo "static code analyze with pylint...."
      - run: echo "pycodestyle (pep8) check with flake8...."
      - run: echo "static type check with mypy...."
      - run: echo "security check with bandit...."

##### deploy #########################################################

  deploy-dev:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy dev project
        run: echo "This job will run after test is complete for $PROJECT_ID"
        env:
          GCP_APP_BUCKET: "PROJECT_DEV_BUCKET_NAME"
          PROJECT_ID: ${{ secrets.GCP_PROJECT_DEV }}
    on:
      push:
        branches:    
          - 'develop'

  deploy-test:
    needs: [test]
    if: contains( github.ref, '/^release.*$/')
    runs-on: ubuntu-latest
    steps:
      - name: deploy dev project
        run: echo "This job will run after test is complete for $PROJECT_ID"
        env:
          GCP_APP_BUCKET: "PROJECT_DEV_BUCKET_NAME"
          PROJECT_ID: ${{ secrets.GCP_PROJECT_TEST }}

  deploy-prod:
    needs: [test]
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: deploy dev project
        run: echo "This job will run after test is complete for $PROJECT_ID"
        env:
          GCP_APP_BUCKET: "PROJECT_DEV_BUCKET_NAME"
          PROJECT_ID: ${{ secrets.GCP_PROJECT_PROD }}

##### publish #########################################################


##### versioning #########################################################


##### test_production #########################################################




